site_name: Foxy
theme:
  name: material

nav:
  - Home: index.md
  - Installation: 1. Installation.md
  - Collector: 2. Collector.md
  - Processor: 3. Processor.md
  - Starship Project: 4. Starship Project.md
  - Xbet Crash Project: 5. Xbet Crash Project.md
  - License: 6. License.md
  
